### ISSUE TITLE
why it is not showing the distance to the objects

### ISSUE THREAD

**Issue by KothapallySrinathReddy** [HassanBinHaroon/YOLOER_V2#5]

**Comment by HassanBinHaroon** [comment]
Please refer to the demo images, the distance is shown in front of the class.

**Comment by KothapallySrinathReddy** [comment]
yoloer_v2  in live cam it is not showing the distances in that demo also

**Comment by HassanBinHaroon** [comment]
@KothapallySrinathReddy Please observe carefully, the distance is float value being appeared in the square brackets adjacent to the object class.
